site_name: 顾宇的实践指南
theme:
  name: material
  language: zh
  highlightjs: true
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换至夜间模式
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换至明亮模式
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top

nav:
  - 首页: index.md
  - 架构:
    - 首页: arch/index.md
    - UML: arch/uml.md
    - 领域驱动设计(DDD):
      - DDD参考大全: arch/ddd/reference.md
      - 领域模型: arch/ddd/domain-model.md
      - 事件风暴: arch/ddd/event-storming.md
      - CQRS: arch/ddd/cqrs.md
    - C4 模型: arch/c4.md
  - 软件工程:
    - 持续探索:
      - 需求:
        - 产品需求模型: se/ce/requirement/requirements-model.md
        - KANO 模型: se/ce/requirement/kano.md
    - 持续集成:
      - 开发: se/ci/dev.md
      - 构建: blank.md
      - 测试: se/ci/test.md
      - 预发布: blank.md
    - 持续部署:
      - 金丝雀发布: se/cd/canary_release.md
      - 蓝绿部署: se/cd/blue_green_deployment.md
      - 优雅关闭: se/cd/graceful_shutdown.md
    - 按需发布:
      - 发布: blank.md
      - 稳定: blank.md
      - 度量: blank.md
      - 学习: blank.md
    - 组织及活动:
      - 敏捷团队:
        - 1. 代办事项梳理会: se/events/iteration/backlog-refinement.md
        - 2. 迭代规划会: se/events/iteration/iteration-planning.md
        - 3. 每日站立会议: se/events/iteration/daily-standup.md
        - 4. 迭代评审会: se/events/iteration/review.md
        - 5. 回顾会: se/events/iteration/retrospective.md
      - ART: blank.md
    - 角色:
      - Scrum Master: se/roles/scrum-master.md
      - 敏捷团队: se/roles/agile-team.md
  - 编程语言:
    - Shell:
      - 首页: programming/shell/index.md
    - Go:
      - 首页: programming/go/index.md
    - HTML:
      - 首页: programming/html/index.md
    - Python:
      - 首页: programming/python/index.md
      - 文件操作: programming/python/file.md
      - 常用包: programming/python/packages.md
    - Java:
      - 首页: programming/java/index.md
    - JavaScript:
      - 首页: programming/js/index.md
    - TypeScript:
      - 首页: programming/ts/index.md
    - Swift:
      - 首页: programming/swift/index.md
  - 移动开发:
    - 首页: mobile/index.md
  - Web 开发:
    - 前端: web/frontend.md
    - 后端: web/backend.md
    - 中间件: web/middleware.md
  - 数据库:
    - MySQL: db/mysql.md
    - SQLite: db/sqlite.md
    - PostgreSQL: db/postgres.md
    - MongoDB: db/mongodb.md
  - 云计算:
    - Kubernetes: cloud/k8s.md
    - Terraform: cloud/terraform.md
  - 安全:
    - 加密与解密: security/encrypt.md
    - 面向开发人员的安全指南: security/develop-guide.md
    - 基于角色的访问控制: security/rbac.md
  - Linux:
    - 命令: linux/command.md
    - FHS: linux/fhs.md
    - systemd: linux/systemd.md
    - ebpf: linux/ebpf.md
    - cattleserver: linux/cattleserver.md
  - 网络:
    - 互联网协议: network/internet.md
    - OSI 模型: network/osi.md
    - DNS: network/dns.md
    - NFS: network/nfs.md
    - LDAP: network/ldap.md
  - 工具:
    - VIM: tools/vim.md
    - Git: tools/git.md
  - 解决方案: solution.md
  - 关于: about.md