site_name: 顾宇的实践指南
theme: 
  name: material
  language: zh
  highlightjs: true
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换至夜间模式
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换至明亮模式
  features:
    - navigation.sections

nav:
  - 主页: index.md
  - 架构:
    - UML: arch/uml.md
  - 领域驱动设计:
    - CQRS: ddd/cqrs.md
    - DDD大全: ddd/reference.md
    - 领域模型: ddd/domain-model.md
    - 事件风暴: ddd/event-storming.md
  - SAFe:
    - 活动: 
      - 产品增量计划(PI): blank.md
      - 迭代(Iteration): 
        - 1. 代办事项梳理会: safe/events/iteration/backlog-refinment.md
        - 2. 迭代规划会: safe/events/iteration/iteration-planning.md
        - 3. 每日站立会议: safe/events/iteration/daily-standup.md
        - 4. 迭代评审会: safe/events/iteration/review.md
        - 5. 回顾会: safe/events/iteration/retrospective.md
    - 角色:
      - Scrum Master: safe/roles/scrum-master.md
      - 敏捷团队: safe/roles/agile-team.md
  - DevOps:
    - 流程阶段:
      - 架构规划: blank.md
      - 需求分析: blank.md
      - 设计: blank.md
      - 开发: blank.md
      - 测试: devops/test.md
      - 部署和发布: blank.md
      - 运维: blank.md
    - 专题:
      - 代码分支: blank.md
    - 落地指南:
      - 开始之前: blank.md
      - 分析组织上下文: blank.md
      - 分析技术上下文: blank.md
      - 制定 DevOps 转型策略: blank.md
      - 使用看板和 DevOps 故事: blank.md
      - 开发驱动的 DevOps 转型: blank.md
      - 运维驱动的 DevOps 转型: blank.md
      - 构建 DevOps 团队: blank.md
  - 知识库:
    - 安全:
      - 基于角色的访问控制: security/rbac.md
    - 编程语言:
      - Shell: programming/shell/index.md
      - Go: programming/go/index.md
      - HTML: programming/html/index.md
      - Python: 
        - 主页: programming/python/index.md
        - 文件操作: programming/python/file.md
        - 常用包: programming/python/packages.md
      - Java: programming/java/index.md
      - JavaScript: programming/js/index.md
      - TypeScript: programming/ts/index.md
    - 前端: frontend/index.md
    - 中间件: middleware/index.md
    - 数据库:
      - MySQL: db/mysql.md
      - Postgres: blank.md
      - Redis: blank.md
      - MongoDB: blank.md
    - Kubernetes: k8s/index.md
    - Linux:
      - 命令: linux/command.md
      - FHS: linux/fhs.md
      - systemd: linux/systemd.md
      - ebpf: linux/ebpf.md
      - cattleserver: linux/cattleserver.md
    - 网络:
      - 互联网协议: network/internet.md
      - OSI 模型: network/osi.md
      - DNS: network/dns.md
      - NFS: network/nfs.md
      - LDAP: network/ldap.md
    - 云计算:
      - AWS: blank.md
      - Azure: blank.md
      - GCP: blank.md
      - 阿里云: blank.md
      - 腾讯云: blank.md
    - vim: vim.md
  - 关于: about.md